### ISSUE TITLE
Flowey outputs blank lines

### ISSUE THREAD

**Issue by quantumdotdot** [crumblingstatue/FloweysTimeMachine#14]
I got an invalid save file on my Neutral run, which when I opened in TextWrangler had several blank lines. When I filled in the values from the original files, the file then worked perfectly. The code might not be capturing those variables fully... if I can get my brain together maybe I can clone it and look at the source but no promises.

Original file: http://pastebin.com/d2EFHeK0
Flowey file: http://pastebin.com/YC1b9Dec

Couldn't upload documents w/o write permissions, hence the pastes. This is Neutral run, pre-endgame.

**Comment by crumblingstatue** [comment]
The problem was with the dropdown selections.

If the program encountered an unknown value, it still set the selection to that value, even though there was no corresponding list item to that value. This made the selection contain an empty string, which when saved back, resulted in an empty line.

I made it so when the program encounters an unknown value for a selection, it tells the user that an unknown value was encountered, and doesn't touch the selection.

I also added the missing values for your save file, so it should work now. Please let me know if it does.

I didn't research what some of those values mean, so I labelled them "Unknown". If you know what an "Unknown" value in your save file stands for, please let me know by opening an issue, or send a pull request adding that value.

**Comment by quantumdotdot** [comment]
Yeah, I'd added the values manually and it worked just fine. I wonder if I can't ferret out what the values are though...

**Comment by crumblingstatue** [comment]
Well, if it works, I'm going to close this issue.
